version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: airvent-db
    environment:
      POSTGRES_USER: airvent
      POSTGRES_PASSWORD: airvent
      POSTGRES_DB: airvent
    ports:
      - "5435:5432" # 호스트:5433 -> 컨테이너:5432
    volumes:
      - airvent-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  airvent-postgres-data:
